### PR TITLE
Added how to setup a new pipeline readme

### LINKED ISSUE #52: Define stepwise instructions for setting up a new pipeline and executing it
**Is your feature request related to a problem? Please describe.**
https://github.com/RADAR-base/radarpipeline/wiki/Mock-Pipeline is pretty sparse and needs more detail. Currently new users are instructed to run mockpipeline but then infer how to use or what the best practices are to use the radarpipeline.

**Describe the solution you'd like**
Provide step-by-step instruction for new users to follow going from creating a new pipeline (ideally from the template repo #39), populating the `config.yaml` and running it

### PR DESCRIPTION
**Pull request by Hsankesara**
Added readme for configuration file & readme for how to set up a new pipeline. 

Fixes #52 #35 #37 #39

### CODE REVIEW

**Comment by Hsankesara** [comment]
@afolarin let me know what else needs to be added here. Would be good to add all the readme updates in this PR.

**Comment by afolarin** [comment]
:+1: Looks nice, a few tweaks here and there to improve, just needs the instructions to be a bit more specific so the naive reader can follow easily.

**Comment by afolarin** [comment]
Though part of me wonders if it is best to place this information into the Wiki so we have a single place to maintain it

**Comment by Hsankesara** [comment]
Going to close this PR for now as I have added the readme updates in the wiki.

**Pull request closed without merging**
